require_relative 'tunes_takeout/food'
require_relative 'tunes_takeout/music'
require_relative 'tunes_takeout/suggestion'
require_relative 'tunes_takeout/favorite'
require_relative 'tunes_takeout/api'
